baseURL = 'https://www.comboink.com/blog/'
title = 'ComboInk Blog | Ink, Toner, Business, Printing, and More'
theme = 'ciBlog'
publishDir = 'blog'
uglyURLs = true
summaryLength= 25
disqusShortname = 'https-www-comboink-com-blog'
disableAliases = true

[permalinks]
  posts = "/posts/:contentbasename"

[params]
    name= 'ComboInk'
    description = 'ComboInk Blog brings you the latest on ink, toner, and printing essentials for home and business. Get DIY tips, SMB advice, and more.'
    dateFormat = "Jan 02, 2006"

[taxonomies]
	authors = "authors"
	tags = "tags"

[outputs]
    home = ["html", "rss"]
    page = ["html"]
    section = ["html"]
    taxonomy = ["html"]
    term = ["html"]

[outputFormats]
    [outputFormats.html]
        ugly = true

[pagination]
    pagerSize = 9
    disableAliases = true